### ISSUE TITLE
Can't create a tunnel anymore

### ISSUE THREAD

**Issue by junglesucks** [boringproxy/boringproxy#99]
So I had to update my vps and I set up my boringproxy once again after that. Ever since then I get
`open /opt/boringproxy/.ssh/authorized_keys: no such file or directory` whenever I try to create a tunnel. It is running as a systemd service. The config is - 
```
[Unit]
Description=boringproxy Admin Server
After=network.target

[Service]
PrivateTmp=true
Type=simple
User=boringproxy
Group=boringproxy
WorkingDirectory=/opt/boringproxy/
ExecStart=/usr/local/bin/boringproxy server -admin-domain bproxy.xxxxxxxx.com

[Install]
WantedBy=multi-user.target
```

**Comment by anderspitman** [comment]
Hey @junglesucks, can you try creating the file as the boringproxy user?

Something like this:

```
mkdir -p /opt/boringproxy/.ssh
touch /opt/boringproxy/.ssh/authorized_keys
chmod 0600 /opt/boringproxy/.ssh/authorized_keys
```

**Comment by anderspitman** [comment]
You may actually only need `mkdir -p /opt/boringproxy/.ssh`

**Comment by junglesucks** [comment]
I did try just making the directory, but got permission denied when running the tunnel.
I'll try with chmod.

**Comment by junglesucks** [comment]
I reset the VPS completely and tried setting up once more. I have the same issue `open /opt/boringproxy/.ssh/authorized_keys: no such file or directory`. This is only when I do it through systemctl, If I were to do it by just running the command there aren't any issues.

**Comment by anderspitman** [comment]
Yeah sounds like a systemd (systemctl) issue. If it works when you run it manually I really don't know what the problem is. My only suggestion would be run it in the exact same directory and setup as when you run it manually.

**Comment by junglesucks** [comment]
My only thought is it could be that its an user permission issue since the manual run is as root user and the systemd one is as boringproxy. I'll look more into it I guess. 

Going on a tangent. I don't know if I should ask this here or if I create a new issue. I've been trying to get docker a docker image up and running.  But I'm getting `x509: certificate signed by unknown authority`. Here's my docker-compose

```
services:
  boringproxy:
    build: ./
    image: boringproxy
    ports:
      - "80:80"
      - "443:443"
    command: ["server", "-admin-domain", "bproxy.xxxxxxxxx.com"]
```

**Comment by anderspitman** [comment]
If you were running it as root then I agree it's probably a permission issue. I would try to get it working as the boringproxy user manually first.

Yeah I'm not going to be much help with the docker stuff, since I specifically tried to make boringproxy simple enough to be distributed/deployed without needing docker.

**Comment by junglesucks** [comment]
Hey, I figured out how to get it done through docker. I updated the docker-compose and the Dockerfile. You could update them in the repository for future reference

Dockerfile
```Dockerfile
FROM golang:1.15-alpine3.12 as builder

WORKDIR /build

RUN apk add git
RUN go get github.com/GeertJohan/go.rice/rice

COPY go.* ./
RUN go mod download
COPY . .

RUN rice embed-go
RUN cd cmd/boringproxy && CGO_ENABLED=0 go build -o boringproxy

FROM alpine 
RUN apk add ca-certificates
EXPOSE 80 443

COPY --from=builder /build/cmd/boringproxy/boringproxy /

ENTRYPOINT ["/boringproxy"]
```

docker-compose.yml
```yaml
services:
  boringproxy-server:
    image: boringproxy
    container_name: boringproxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /root/boringproxy/boringproxy_db.json:/boringproxy_db.json
    command: ["server", "-admin-server", "bp.example.com"]
```
